### ISSUE TITLE
Adding offset to DatetimeIndex is broken

### ISSUE THREAD

**Issue by tonymastrorio** [tonymastrorio/Test-Repo#3]
Code Sample, a copy-pastable example if possible
```
import pandas as pd
offset = pd.DateOffset(months=3, days=10)
dates = pd.date_range(start='01 Jan 2014', end='01 Jan 2017', freq='AS')
dates + offset
```

Problem description

ValueError is raised:

```
Traceback (most recent call last):
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\core\arrays\datetimelike.py", line 884, in _validate_frequency
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\core\indexes\datetimelike.py", line 489, in __add__
    result = self._data.__add__(maybe_unwrap_index(other))
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\core\arrays\datetimelike.py", line 1190, in __add__
    result = self._add_offset(other)
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\core\arrays\datetimes.py", line 737, in _add_offset
    result = offset.apply_index(values)
  File "pandas/_libs/tslibs/offsets.pyx", line 116, in pandas._libs.tslibs.offsets.apply_index_wraps.wrapper
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\tseries\offsets.py", line 278, in apply_index
    i = type(i)(shifted, freq=i.freq, dtype=i.dtype)
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\core\arrays\datetimes.py", line 351, in __init__
    type(self)._validate_frequency(self, freq)
  File "C:\mma\local\Anaconda3\envs\pd24\lib\site-packages\pandas\core\arrays\datetimelike.py", line 897, in _validate_frequency
    .format(infer=inferred, passed=freq.freqstr))
ValueError: Inferred frequency AS-APR from passed values does not conform to passed frequency AS-JAN
```

**Comment by tonymastrorio** [comment]
Thanks for submitting this issue! I've imported it into DevFlight, which makes it easy to get your open-source issues resolved faster. 
			If you're interested in receiving a proposal to have [your issue](http://localhost:3000/projects/20/user_issues/56) prioritized, you can claim it by selecting 'Claim Issue' and I'll be in touch!

**Comment by tonymastrorio** [comment]
Test message. Here's your [imported issue](http://localhost:3000/projects/20/user_issues/72).

**Comment by tonymastrorio** [comment]
Thanks for submitting this issue! I've imported it into DevFlight, which makes it easy to get your open-source issues resolved faster. 
				If you're interested in receiving a proposal to have [your issue](https://devflight.com/projects/9/user_issues/19) prioritized, you can claim it by selecting 'Claim Issue' and I'll be in touch!
